// Bump the patch version everywhere and stamp a build time, so the version
// visibly progresses on each packaged build.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const pkgPath = resolve(root, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const [maj, min, pat] = pkg.version.split(".").map(Number);
pkg.version = `${maj}.${min}.${pat + 1}`;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

const manPath = resolve(root, "extension/manifest.json");
const man = JSON.parse(readFileSync(manPath, "utf8"));
man.version = pkg.version;
writeFileSync(manPath, JSON.stringify(man, null, 2) + "\n");

const build = new Date().toISOString().slice(0, 16).replace("T", " ");
writeFileSync(
  resolve(root, "src/version.ts"),
  `// AUTO-GENERATED by scripts/bump-version.mjs — do not edit by hand.\n` +
  `export const VERSION = "${pkg.version}";\n` +
  `export const BUILD = "${build}";\n`,
);

console.log("bumped to", pkg.version, "(" + build + ")");
